In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import accuracy_score
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import RandomizedSearchCV
from numpy import array
from sklearn.model_selection import KFold
from sklearn.tree import DecisionTreeClassifier
import sklearn

In [2]:
dfXTrain=pd.read_csv("E:\ids\dataset_uci\\final_X_train.txt", header=None)
dfyTrain=pd.read_csv("E:\ids\dataset_uci\\final_y_train.txt", header=None)
dfXTest=pd.read_csv("E:\ids\dataset_uci\\final_X_test.txt", header=None)
dfyTest=pd.read_csv("E:\ids\dataset_uci\\final_y_test.txt", header=None)


In [3]:
x=dfXTrain.values
x= np.vstack([x, dfXTest.values])
y=dfyTrain.values
y= np.vstack([y, dfyTest.values])
y=np.append(y, x, axis=1)
np.random.shuffle(y)
x=y[:, 1:]
y=y[:, 0]
print(x.shape)
print(y.shape)
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=1/5, shuffle=True, random_state=42)
print(y_test.shape)
print(y_train.shape)

(5744, 561)
(5744,)
(1149,)
(4595,)


KNN

In [23]:
parameter_grid = {'n_neighbors': list(range(1,5)), 'p': [1, 2, 3, 4.7]}
grid_search = GridSearchCV(estimator = KNeighborsClassifier(), param_grid=parameter_grid, scoring='accuracy', cv=5, 
                           return_train_score=True, iid=False, n_jobs=-1)
grid_search.fit(X_train, y_train)
y_estimated = grid_search.predict(X_test)
print(accuracy_score(y_test, y_estimated))
print(grid_search.best_params_)
print(sklearn.metrics.f1_score(y_test, y_estimated, average=None))

0.9608355091383812
{'n_neighbors': 1, 'p': 1}
[0.96585366 0.96571429 0.96610169 0.93896714 0.94840295 0.98575499]


In [27]:
y_estimated2 = grid_search.predict(X_train)
print(sklearn.metrics.f1_score(y_train, y_estimated2, average=None))
print(sklearn.metrics.accuracy_score(y_train, y_estimated2))

[1. 1. 1. 1. 1. 1.]
1.0


In [32]:
parameter_grid = {'n_neighbors': list(range(1,5)), 'p': [1, 2, 3, 4.7]}
X_trainR, X_testR, y_trainR, y_testR = train_test_split(x, y, test_size=1/5,shuffle=True, random_state=42)
gs_random = RandomizedSearchCV(estimator=KNeighborsClassifier(), param_distributions=parameter_grid, cv= 5,n_iter=16)
gs_random.fit(X_trainR, y_trainR)
y_estimated = gs_random.predict(X_testR)
print(accuracy_score(y_testR, y_estimated))
print(sklearn.metrics.f1_score(y_testR, y_estimated, average=None))

0.9608355091383812
[0.96585366 0.96571429 0.96610169 0.93896714 0.94840295 0.98575499]


DecisionTree

In [5]:
X_trainT, X_testT, y_trainT, y_testT = train_test_split(x, y, test_size=1/5,shuffle=True, random_state=42)
params = {'max_features': ['auto', 'sqrt', 'log2'],
          'min_samples_split':list(range(2,15)), 
          'min_samples_leaf':list(range(2,11)),
         }
grid_search = GridSearchCV(estimator = DecisionTreeClassifier(), param_grid=params, scoring='accuracy', cv=5, 
                           return_train_score=True, iid=False)
grid_search.fit(X_trainT, y_trainT)
y_estimated = grid_search.predict(X_testT)
print(accuracy_score(y_testT, y_estimated))
print(grid_search.best_params_)
print(sklearn.metrics.f1_score(y_testT, y_estimated, average=None))

0.7902523933855526
{'max_features': 'auto', 'min_samples_leaf': 8, 'min_samples_split': 10}
[0.76122931 0.69467787 0.71186441 0.82648402 0.83937824 0.90588235]


In [11]:
y_estimated2 = grid_search.predict(X_trainT)
print(accuracy_score(y_trainT, y_estimated2))
print(sklearn.metrics.f1_score(y_trainT, y_estimated2, average=None))

0.9997823721436344
[1.         1.         1.         0.99944843 0.99939795 1.        ]


In [6]:
gs_random = RandomizedSearchCV(estimator=DecisionTreeClassifier(), param_distributions=params, cv= 5,n_iter=100)
gs_random.fit(X_trainT, y_trainT)
print (gs_random.best_params_)
y_estimated = gs_random.predict(X_testT)
print(accuracy_score(y_testT, y_estimated))
print(grid_search.best_params_)
print(sklearn.metrics.f1_score(y_testT, y_estimated, average=None))

{'min_samples_split': 8, 'min_samples_leaf': 4, 'max_features': 'auto'}
0.7771975630983464
{'max_features': 'auto', 'min_samples_leaf': 8, 'min_samples_split': 10}
[0.75961538 0.73352436 0.68926554 0.77729258 0.82077922 0.88690476]


In [13]:
y_estimatedF = gs_randomF.predict(X_trainF)
print(accuracy_score(y_trainF, y_estimatedF))
print(sklearn.metrics.f1_score(y_trainF, y_estimatedF, average=None))

0.9993471164309031
[1.         0.99853372 0.99933643 0.99889746 0.99939795 1.        ]


Random forest

In [7]:
from sklearn.ensemble import RandomForestClassifier

paramsF = {'criterion':['gini','entropy'],
          'n_estimators':[10,15,20,25,30],
          'min_samples_leaf':[1,2,3],
          'min_samples_split':[3,4,5,6,7]}
X_trainF, X_testF, y_trainF, y_testF = train_test_split(x, y, test_size=1/5,shuffle=True, random_state=42)
grid_search = GridSearchCV(estimator = RandomForestClassifier(), param_grid=paramsF, scoring='accuracy', cv=5, 
                           return_train_score=True, iid=False)
grid_search.fit(X_trainF, y_trainF)
y_estimated = grid_search.predict(X_testF)
print(accuracy_score(y_testF, y_estimated))
print(grid_search.best_params_)
print(sklearn.metrics.f1_score(y_testF, y_estimated, average=None))

0.9155787641427328
{'criterion': 'entropy', 'min_samples_leaf': 1, 'min_samples_split': 4, 'n_estimators': 25}
[0.92307692 0.89204545 0.87861272 0.90686275 0.91428571 0.97752809]


In [15]:
y_estimated = grid_search.predict(X_trainF)
print(accuracy_score(y_trainF, y_estimated))
print(grid_search.best_params_)
print(sklearn.metrics.f1_score(y_trainF, y_estimated, average=None))

0.9997823721436344
{'criterion': 'entropy', 'min_samples_leaf': 1, 'min_samples_split': 4, 'n_estimators': 25}
[1.         1.         1.         0.99944843 0.99939795 1.        ]


In [8]:
gs_randomF = RandomizedSearchCV(estimator=RandomForestClassifier(), param_distributions=paramsF, cv= 5,n_iter=100)
gs_randomF.fit(X_trainF, y_trainF)
print (gs_randomF.best_params_)
y_estimatedF = gs_randomF.predict(X_testF)
print(accuracy_score(y_testF, y_estimatedF))
print(sklearn.metrics.f1_score(y_testF, y_estimatedF, average=None))

{'n_estimators': 25, 'min_samples_split': 6, 'min_samples_leaf': 1, 'criterion': 'gini'}
0.9120974760661444
[0.91686461 0.89772727 0.89017341 0.8997555  0.90647482 0.9631728 ]


In [17]:
y_estimatedF = gs_randomF.predict(X_trainF)
print(accuracy_score(y_trainF, y_estimatedF))
print(sklearn.metrics.f1_score(y_trainF, y_estimatedF, average=None))

0.9993471164309031
[1.         0.99853372 0.99933643 0.99889746 0.99939795 1.        ]


SVM

In [18]:
from sklearn import svm
paramsS = {'C': [6,7,8,9,10,11,12], 
          'kernel': ['linear','rbf']}
X_trainS, X_testS, y_trainS, y_testS = train_test_split(x, y, test_size=1/5,shuffle=True, random_state=42)
grid_searchS = GridSearchCV(estimator = svm.SVC(gamma='auto'), param_grid=paramsS, scoring='accuracy', cv=5, 
                           return_train_score=True, iid=False)
grid_searchS.fit(X_trainS, y_trainS)
y_estimatedS = grid_searchS.predict(X_testS)
print(accuracy_score(y_testS, y_estimatedS))
print(grid_searchS.best_params_)
print(sklearn.metrics.f1_score(y_testS, y_estimatedS, average=None))

0.9060052219321149
{'C': 6, 'kernel': 'linear'}
[0.92565947 0.88950276 0.87315634 0.87735849 0.88557214 0.98870056]


In [20]:
y_estimatedS = grid_searchS.predict(X_trainS)
print(accuracy_score(y_trainS, y_estimatedS))
print(sklearn.metrics.f1_score(y_trainS, y_estimatedS, average=None))

0.9780195865070729
[1.         0.99707174 0.99734396 0.94614103 0.94202032 1.        ]


In [21]:
gs_randomS = RandomizedSearchCV(estimator=svm.SVC(gamma='auto'), param_distributions=paramsS, cv= 5,n_iter=100)
gs_randomS.fit(X_trainS, y_trainS)
print (gs_randomS.best_params_)
y_estimatedS = gs_randomS.predict(X_testS)
print(accuracy_score(y_testS, y_estimatedS))
print(sklearn.metrics.f1_score(y_testS, y_estimatedS, average=None))

C:\Users\Mioara\Anaconda3\lib\site-packages\sklearn\model_selection\_search.py:271: UserWarning: The total space of parameters 14 is smaller than n_iter=100. Running 14 iterations. For exhaustive searches, use GridSearchCV.
  % (grid_size, self.n_iter, grid_size), UserWarning)


{'kernel': 'linear', 'C': 6}
0.9060052219321149
[0.92565947 0.88950276 0.87315634 0.87735849 0.88557214 0.98870056]


In [28]:
y_estimatedS = gs_randomS.predict(X_trainS)
print(accuracy_score(y_trainS, y_estimatedS))
print(sklearn.metrics.f1_score(y_trainS, y_estimatedS, average=None))

0.9780195865070729
[1.         0.99707174 0.99734396 0.94614103 0.94202032 1.        ]


Multi-layer Perceptron classifier

In [ ]:
from sklearn.neural_network import MLPClassifier
paramsM = {'activation' : ['identity', 'logistic', 'tanh', 'relu'], 
          'solver' : ['lbfgs', 'sgd', 'adam'],
          'alpha':[0.1, 0.001, 0.0001]}
X_trainM, X_testM, y_trainM, y_testM = train_test_split(x, y, test_size=1/5,shuffle=True, random_state=42)
grid_searchM = GridSearchCV(estimator = MLPClassifier(max_iter=10000), param_grid=paramsM, scoring='accuracy', cv=5, 
                           return_train_score=True, iid=False)
grid_searchM.fit(X_trainM, y_trainM)
y_estimatedM = grid_searchM.predict(X_testM)
print(accuracy_score(y_testM, y_estimatedM))
print(grid_searchM.best_params_)
print(sklearn.metrics.f1_score(y_testM, y_estimatedM, average=None))

In [ ]:
y_estimatedM = grid_searchM.predict(X_testM)
print(accuracy_score(y_testM, y_estimatedM))
print(f1_score(y_testM, y_estimatedM, average=None))

In [ ]:
gs_randomM = RandomizedSearchCV(estimator=MLPClassifier(max_iter=10000), param_distributions=paramsM, cv= 5,n_iter=100)
gs_randomM.fit(X_trainM, y_trainM)
print (gs_randomM.best_params_)
y_estimatedM = gs_randomM.predict(X_testM)
print(accuracy_score(y_testM, y_estimatedM))
print(sklearn.metrics.f1_score(y_testM, y_estimatedM, average=None))

In [ ]:
y_estimatedM = gs_randomM.predict(X_trainM)
print(accuracy_score(y_trainM, y_estimatedM))
print(f1_score(y_trainM, y_estimatedM, average=None))