In [15]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import accuracy_score
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import RandomizedSearchCV
from numpy import array
from sklearn.model_selection import KFold
from sklearn.tree import DecisionTreeClassifier
import sklearn
from sklearn.metrics import f1_score

In [7]:
import seaborn as sns
planets = sns.load_dataset('planets')
planets=planets.dropna()
planets=planets.drop(columns=["method"])
#planets

In [8]:
from sklearn.preprocessing import MinMaxScaler
x=planets.values[:,1:]
scaler = MinMaxScaler()
scaler.fit(x)
x = scaler.transform(x)
print(x.shape)
y=planets.values[:, 0]
print(y.shape)
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=1/5, shuffle=True, random_state=42)
print(y_test.shape)
print(y_train.shape)

(498, 4)
(498,)
(100,)
(398,)


In [13]:
planets[0:5]
y_test

array([3., 4., 1., 1., 1., 2., 1., 1., 1., 2., 1., 1., 1., 6., 1., 1., 2.,
       1., 1., 3., 2., 1., 1., 1., 6., 1., 1., 1., 1., 3., 3., 4., 2., 1.,
       1., 2., 1., 3., 2., 1., 1., 2., 1., 1., 1., 1., 1., 1., 2., 1., 2.,
       1., 1., 6., 5., 1., 1., 1., 2., 2., 1., 4., 1., 1., 2., 1., 2., 3.,
       1., 1., 3., 2., 1., 3., 1., 2., 1., 1., 2., 2., 1., 3., 2., 1., 1.,
       2., 3., 2., 2., 1., 1., 1., 4., 1., 1., 1., 2., 5., 1., 1.])

KNN

In [26]:
parameter_grid = {'n_neighbors': list(range(1,10)), 'p': [1, 2, 3, 4.7]}
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=1/5, shuffle=True, random_state=42)
grid_search = GridSearchCV(estimator = KNeighborsClassifier(), param_grid=parameter_grid, scoring='accuracy', cv=5, 
                           return_train_score=True, iid=False)
grid_search.fit(X_train, y_train)
y_estimated = grid_search.predict(X_test)
print(f1_score(y_test, y_estimated, average=None))
print(accuracy_score(y_test, y_estimated))
print(grid_search.best_params_)

C:\Users\Mioara\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:652: Warning: The least populated class in y has only 2 members, which is too few. The minimum number of members in any class cannot be less than n_splits=5.
  % (min_groups, self.n_splits)), Warning)


[0.79699248 0.45714286 0.42857143 0.28571429 0.         0.66666667]
0.68
{'n_neighbors': 2, 'p': 1}


C:\Users\Mioara\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [16]:
y_estimated2 = grid_search.predict(X_train)
print(f1_score(y_train, y_estimated2, average=None))
print(accuracy_score(y_train, y_estimated2))

[0.88555347 0.66666667 0.6875     0.66666667 0.         0.96551724]
0.8241206030150754


C:\Users\Mioara\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [27]:
X_trainR, X_testR, y_trainR, y_testR = train_test_split(x, y, test_size=1/5,shuffle=True, random_state=42)
gs_random = RandomizedSearchCV(estimator=KNeighborsClassifier(), param_distributions=parameter_grid, cv= 5,n_iter=100)
gs_random.fit(X_trainR, y_trainR)
print (gs_random.best_params_)
y_estimated = grid_search.predict(X_testR)
print(accuracy_score(y_testR, y_estimated))
print(f1_score(y_test, y_estimated, average=None))

C:\Users\Mioara\Anaconda3\lib\site-packages\sklearn\model_selection\_search.py:271: UserWarning: The total space of parameters 36 is smaller than n_iter=100. Running 36 iterations. For exhaustive searches, use GridSearchCV.
  % (grid_size, self.n_iter, grid_size), UserWarning)
C:\Users\Mioara\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:652: Warning: The least populated class in y has only 2 members, which is too few. The minimum number of members in any class cannot be less than n_splits=5.
  % (min_groups, self.n_splits)), Warning)


{'p': 1, 'n_neighbors': 2}
0.68
[0.79699248 0.45714286 0.42857143 0.28571429 0.         0.66666667]


C:\Users\Mioara\Anaconda3\lib\site-packages\sklearn\model_selection\_search.py:841: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)
C:\Users\Mioara\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [18]:
y_estimated2 = gs_random.predict(X_trainR)
print(accuracy_score(y_trainR, y_estimated2))
print(f1_score(y_trainR, y_estimated2, average=None))

0.8241206030150754
[0.88555347 0.66666667 0.6875     0.66666667 0.         0.96551724]


C:\Users\Mioara\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


DecisionTree

In [28]:
X_trainT, X_testT, y_trainT, y_testT = train_test_split(x, y, test_size=1/5,shuffle=True, random_state=42)
params = {'max_features': ['auto', 'sqrt', 'log2'],
          'min_samples_split':list(range(2,15)), 
          'min_samples_leaf':list(range(2,11)),
         }
grid_search = GridSearchCV(estimator = DecisionTreeClassifier(), param_grid=params, scoring='accuracy', cv=5, 
                           return_train_score=True, iid=False)
grid_search.fit(X_trainT, y_trainT)
y_estimated = grid_search.predict(X_testT)
print(accuracy_score(y_testT, y_estimated))
print(grid_search.best_params_)
print(f1_score(y_testT, y_estimated, average=None))

C:\Users\Mioara\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:652: Warning: The least populated class in y has only 2 members, which is too few. The minimum number of members in any class cannot be less than n_splits=5.
  % (min_groups, self.n_splits)), Warning)


0.63
{'max_features': 'log2', 'min_samples_leaf': 9, 'min_samples_split': 7}
[0.76923077 0.46153846 0.         0.44444444 0.         0.66666667]


C:\Users\Mioara\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [20]:
y_estimated2 = grid_search.predict(X_trainT)
print(accuracy_score(y_trainT, y_estimated2))
print(f1_score(y_trainT, y_estimated2, average=None))

0.7160804020100503
[0.82352941 0.54857143 0.33333333 0.69565217 0.         0.625     ]


C:\Users\Mioara\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [29]:
gs_random = RandomizedSearchCV(estimator=DecisionTreeClassifier(), param_distributions=params, cv= 5,n_iter=100)
gs_random.fit(X_trainT, y_trainT)
print (gs_random.best_params_)
y_estimated = gs_random.predict(X_testT)
print(accuracy_score(y_testT, y_estimated))
print(grid_search.best_params_)
print(f1_score(y_testT, y_estimated, average=None))

C:\Users\Mioara\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:652: Warning: The least populated class in y has only 2 members, which is too few. The minimum number of members in any class cannot be less than n_splits=5.
  % (min_groups, self.n_splits)), Warning)


{'min_samples_split': 3, 'min_samples_leaf': 10, 'max_features': 'sqrt'}
0.56
{'max_features': 'log2', 'min_samples_leaf': 9, 'min_samples_split': 7}
[0.73170732 0.28571429 0.38461538 0.         0.         0.        ]


C:\Users\Mioara\Anaconda3\lib\site-packages\sklearn\model_selection\_search.py:841: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)
C:\Users\Mioara\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [22]:
y_estimated2 = gs_random.predict(X_trainT)
print(accuracy_score(y_trainT, y_estimated2))
print(f1_score(y_trainT, y_estimated2, average=None))

0.6909547738693468
[0.816      0.58695652 0.2295082  0.42105263 0.         0.4       ]


C:\Users\Mioara\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


Random forest

In [30]:
from sklearn.ensemble import RandomForestClassifier

paramsF = {'criterion':['gini','entropy'],
          'n_estimators':[10,15,20,25,30],
          'min_samples_leaf':[1,2,3],
          'min_samples_split':[3,4,5,6,7]}
X_trainF, X_testF, y_trainF, y_testF = train_test_split(x, y, test_size=1/5,shuffle=True, random_state=42)
grid_search = GridSearchCV(estimator = RandomForestClassifier(), param_grid=paramsF, scoring='accuracy', cv=5, 
                           return_train_score=True, iid=False)
grid_search.fit(X_trainF, y_trainF)
y_estimated = grid_search.predict(X_testF)
print(accuracy_score(y_testF, y_estimated))
print(grid_search.best_params_)
print(f1_score(y_testF, y_estimated, average=None))

C:\Users\Mioara\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:652: Warning: The least populated class in y has only 2 members, which is too few. The minimum number of members in any class cannot be less than n_splits=5.
  % (min_groups, self.n_splits)), Warning)


0.66
{'criterion': 'entropy', 'min_samples_leaf': 1, 'min_samples_split': 4, 'n_estimators': 15}
[0.78461538 0.42424242 0.28571429 0.57142857 0.         0.85714286]


C:\Users\Mioara\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [31]:
gs_randomF = RandomizedSearchCV(estimator=RandomForestClassifier(), param_distributions=paramsF, cv= 5,n_iter=100)
gs_randomF.fit(X_trainF, y_trainF)
print (gs_randomF.best_params_)
y_estimatedF = gs_randomF.predict(X_testF)
print(accuracy_score(y_testF, y_estimatedF))
print(f1_score(y_testF, y_estimatedF, average=None))

C:\Users\Mioara\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:652: Warning: The least populated class in y has only 2 members, which is too few. The minimum number of members in any class cannot be less than n_splits=5.
  % (min_groups, self.n_splits)), Warning)


{'n_estimators': 20, 'min_samples_split': 6, 'min_samples_leaf': 2, 'criterion': 'entropy'}
0.68
[0.80620155 0.5        0.23529412 0.4        0.         0.85714286]


C:\Users\Mioara\Anaconda3\lib\site-packages\sklearn\model_selection\_search.py:841: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)
C:\Users\Mioara\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [25]:
y_estimated = grid_search.predict(X_trainF)
print(accuracy_score(y_trainF, y_estimated))
print(grid_search.best_params_)
print(f1_score(y_trainF, y_estimated, average=None))

0.9824120603015075
{'criterion': 'entropy', 'min_samples_leaf': 1, 'min_samples_split': 4, 'n_estimators': 25}
[0.98538622 0.96703297 0.98795181 1.         1.         1.        ]


SVM

In [32]:
from sklearn import svm
paramsS = {'C': [6,7,8,9,10,11,12], 
          'kernel': ['linear','rbf']}
X_trainS, X_testS, y_trainS, y_testS = train_test_split(x, y, test_size=1/5,shuffle=True, random_state=42)
grid_searchS = GridSearchCV(estimator = svm.SVC(gamma='auto'), param_grid=paramsS, scoring='accuracy', cv=5, 
                           return_train_score=True, iid=False)
grid_searchS.fit(X_trainS, y_trainS)
y_estimatedS = grid_searchS.predict(X_testS)
print(accuracy_score(y_testS, y_estimatedS))
print(grid_searchS.best_params_)
print(f1_score(y_testS, y_estimatedS, average=None))

C:\Users\Mioara\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:652: Warning: The least populated class in y has only 2 members, which is too few. The minimum number of members in any class cannot be less than n_splits=5.
  % (min_groups, self.n_splits)), Warning)


0.58
{'C': 6, 'kernel': 'linear'}
[0.73417722 0.         0.         0.         0.         0.        ]


C:\Users\Mioara\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [33]:
gs_randomS = RandomizedSearchCV(estimator=svm.SVC(gamma='auto'), param_distributions=paramsS, cv= 5,n_iter=100)
gs_randomS.fit(X_trainS, y_trainS)
print (gs_randomS.best_params_)
y_estimatedS = gs_randomS.predict(X_testS)
print(accuracy_score(y_testS, y_estimatedS))
print(f1_score(y_testS, y_estimatedS, average=None))

C:\Users\Mioara\Anaconda3\lib\site-packages\sklearn\model_selection\_search.py:271: UserWarning: The total space of parameters 14 is smaller than n_iter=100. Running 14 iterations. For exhaustive searches, use GridSearchCV.
  % (grid_size, self.n_iter, grid_size), UserWarning)
C:\Users\Mioara\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:652: Warning: The least populated class in y has only 2 members, which is too few. The minimum number of members in any class cannot be less than n_splits=5.
  % (min_groups, self.n_splits)), Warning)


{'kernel': 'linear', 'C': 6}
0.58
[0.73417722 0.         0.         0.         0.         0.        ]


C:\Users\Mioara\Anaconda3\lib\site-packages\sklearn\model_selection\_search.py:841: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)
C:\Users\Mioara\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


Multi-layer Perceptron classifier

In [35]:
from sklearn.neural_network import MLPClassifier
paramsM = {'activation' : ['identity', 'logistic', 'tanh', 'relu'], 
          'solver' : ['lbfgs', 'sgd', 'adam'],
          'alpha':[0.1, 0.001, 0.0001]}
X_trainM, X_testM, y_trainM, y_testM = train_test_split(x, y, test_size=1/5,shuffle=True, random_state=42)
grid_searchM = GridSearchCV(estimator = MLPClassifier(max_iter=10000), param_grid=paramsM, scoring='accuracy', cv=5, 
                           return_train_score=True, iid=False, n_jobs=-1)
grid_searchM.fit(X_trainM, y_trainM)
y_estimatedM = grid_searchM.predict(X_testM)
print(accuracy_score(y_testM, y_estimatedM))
print(grid_searchM.best_params_)
print(f1_score(y_testM, y_estimatedM, average=None))

C:\Users\Mioara\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:652: Warning: The least populated class in y has only 2 members, which is too few. The minimum number of members in any class cannot be less than n_splits=5.
  % (min_groups, self.n_splits)), Warning)


0.63
{'activation': 'relu', 'alpha': 0.001, 'solver': 'adam'}
[0.78461538 0.35       0.25       0.28571429 0.         0.8       ]


C:\Users\Mioara\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [37]:
gs_randomM = RandomizedSearchCV(estimator=MLPClassifier(max_iter=10000), param_distributions=paramsM, cv= 5,n_iter=100)
gs_randomM.fit(X_trainM, y_trainM)
print (gs_randomM.best_params_)
y_estimatedM = gs_randomM.predict(X_testM)
print(accuracy_score(y_testM, y_estimatedM))
print(f1_score(y_testM, y_estimatedM, average=None))

C:\Users\Mioara\Anaconda3\lib\site-packages\sklearn\model_selection\_search.py:271: UserWarning: The total space of parameters 36 is smaller than n_iter=100. Running 36 iterations. For exhaustive searches, use GridSearchCV.
  % (grid_size, self.n_iter, grid_size), UserWarning)
C:\Users\Mioara\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:652: Warning: The least populated class in y has only 2 members, which is too few. The minimum number of members in any class cannot be less than n_splits=5.
  % (min_groups, self.n_splits)), Warning)
C:\Users\Mioara\Anaconda3\lib\site-packages\sklearn\model_selection\_search.py:841: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)


{'solver': 'adam', 'alpha': 0.001, 'activation': 'relu'}
0.61
[0.77862595 0.31578947 0.125      0.28571429 0.         0.66666667]


C:\Users\Mioara\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [38]:
y_estimatedM = gs_randomM.predict(X_trainM)
print(accuracy_score(y_trainM, y_estimatedM))
print(f1_score(y_trainM, y_estimatedM, average=None))

0.6708542713567839
[0.80073126 0.41891892 0.35483871 0.26666667 0.         0.36363636]


C:\Users\Mioara\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
