In [5]:
import pandas as pd
import numpy as np

In [6]:
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import accuracy_score
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import RandomizedSearchCV
from numpy import array
from sklearn.model_selection import KFold
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import f1_score
import sklearn

In [7]:
adress='http://archive.ics.uci.edu/ml/machine-learning-databases/00422/wifi_localization.txt'
dataframe=pd.read_csv(adress,sep="\t",header=None)
dataframe

0   1   2   3   4   5   6  7
0    -64 -56 -61 -66 -71 -82 -81  1
1    -68 -57 -61 -65 -71 -85 -85  1
2    -63 -60 -60 -67 -76 -85 -84  1
3    -61 -60 -68 -62 -77 -90 -80  1
4    -63 -65 -60 -63 -77 -81 -87  1
5    -64 -55 -63 -66 -76 -88 -83  1
6    -65 -61 -65 -67 -69 -87 -84  1
7    -61 -63 -58 -66 -74 -87 -82  1
8    -65 -60 -59 -63 -76 -86 -82  1
9    -62 -60 -66 -68 -80 -86 -91  1
10   -67 -61 -62 -67 -77 -83 -91  1
11   -65 -59 -61 -67 -72 -86 -81  1
12   -63 -57 -61 -65 -73 -84 -84  1
13   -66 -60 -65 -62 -70 -85 -83  1
14   -61 -59 -65 -63 -74 -89 -87  1
15   -67 -60 -59 -61 -71 -86 -91  1
16   -63 -56 -60 -62 -70 -84 -91  1
17   -60 -54 -59 -65 -73 -83 -84  1
18   -60 -58 -60 -61 -73 -84 -88  1
19   -62 -59 -63 -64 -70 -84 -84  1
20   -63 -59 -64 -66 -72 -84 -90  1
21   -65 -59 -66 -65 -68 -82 -85  1
22   -63 -56 -63 -65 -72 -82 -89  1
23   -67 -60 -66 -65 -75 -86 -87  1
24   -63 -57 -67 -66 -79 -86 -89  1
25   -66 -59 -64 -68 -68 -97 -83  1
26   -65 -61 -64 -68 -77 -86 -89  1
27   -66 -57 -65 -69 -78 -85 -85  1
28   -67 -57 -64 -71 -75 -89 -87  1
29   -65 -62 -62 -65 -77 -84 -85  1
...   ..  ..  ..  ..  ..  ..  .. ..
1970 -58 -55 -50 -54 -48 -80 -86  4
1971 -61 -51 -52 -56 -47 -86 -90  4
1972 -60 -52 -51 -55 -48 -86 -90  4
1973 -63 -61 -49 -58 -46 -92 -83  4
1974 -61 -54 -45 -54 -43 -88 -80  4
1975 -57 -53 -45 -54 -52 -84 -82  4
1976 -56 -60 -47 -58 -46 -80 -82  4
1977 -55 -57 -43 -59 -53 -81 -85  4
1978 -55 -54 -43 -60 -51 -84 -88  4
1979 -56 -55 -45 -59 -52 -84 -86  4
1980 -55 -54 -46 -60 -50 -84 -86  4
1981 -56 -54 -47 -59 -52 -84 -91  4
1982 -56 -55 -44 -61 -51 -84 -87  4
1983 -57 -55 -48 -59 -51 -81 -86  4
1984 -59 -54 -49 -58 -52 -83 -93  4
1985 -58 -53 -46 -59 -50 -86 -90  4
1986 -56 -55 -44 -60 -51 -84 -86  4
1987 -56 -53 -43 -61 -58 -80 -85  4
1988 -57 -55 -50 -57 -49 -84 -85  4
1989 -56 -55 -54 -61 -46 -79 -79  4
1990 -57 -54 -49 -61 -43 -79 -85  4
1991 -59 -53 -45 -57 -45 -81 -82  4
1992 -57 -56 -53 -62 -48 -87 -88  4
1993 -63 -55 -50 -63 -50 -91 -85  4
1994 -61 -54 -51 -63 -44 -87 -88  4
1995 -59 -59 -48 -66 -50 -86 -94  4
1996 -59 -56 -50 -62 -47 -87 -90  4
1997 -62 -59 -46 -65 -45 -87 -88  4
1998 -62 -58 -52 -61 -41 -90 -85  4
1999 -59 -50 -45 -60 -45 -88 -87  4

[2000 rows x 8 columns]

In [8]:
from sklearn.preprocessing import MinMaxScaler

x=dataframe.values[:,:-1]
scaler = MinMaxScaler()
scaler.fit(x)
x = scaler.transform(x)
print(x.shape)
y=dataframe.values[:, -1]
print(y.shape)
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=1/5, shuffle=True, random_state=42)
print(y_test.shape)
print(y_train.shape)

(2000, 7)
(2000,)
(400,)
(1600,)


C:\Users\Florina\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)


In [10]:
parameter_grid = {'n_neighbors': list(range(1,10)), 'p': [1, 2, 3, 4.7]}
grid_search = GridSearchCV(estimator = KNeighborsClassifier(), param_grid=parameter_grid, scoring='accuracy', cv=5, 
                           return_train_score=True, iid=False)
grid_search.fit(X_train, y_train)
y_estimated = grid_search.predict(X_test)
print(f1_score(y_test, y_estimated, average=None))
print(accuracy_score(y_test, y_estimated))
print(grid_search.best_params_)

[0.99038462 0.96216216 0.95081967 0.99107143]
0.975
{'n_neighbors': 3, 'p': 2}


In [12]:
y_estimated2 = grid_search.predict(X_train)
print(f1_score(y_train, y_estimated2, average=None))
print(accuracy_score(y_train, y_estimated2))

[0.99496222 0.99380421 0.98669891 0.99481865]
0.9925


In [15]:
X_trainR, X_testR, y_trainR, y_testR = train_test_split(x, y, test_size=1/5,shuffle=True, random_state=42)
gs_random = RandomizedSearchCV(estimator=KNeighborsClassifier(), param_distributions=parameter_grid, cv= 5,n_iter=100)
gs_random.fit(X_trainR, y_trainR)
print (gs_random.best_params_)
y_estimated = gs_random.predict(X_test)
print(accuracy_score(y_test, y_estimated))
print(f1_score(y_test, y_estimated, average=None))

C:\Users\Florina\Anaconda3\lib\site-packages\sklearn\model_selection\_search.py:271: UserWarning: The total space of parameters 36 is smaller than n_iter=100. Running 36 iterations. For exhaustive searches, use GridSearchCV.
  % (grid_size, self.n_iter, grid_size), UserWarning)


{'p': 2, 'n_neighbors': 3}
0.975
[0.99038462 0.96216216 0.95081967 0.99107143]


In [16]:
y_estimated2 = gs_random.predict(X_trainR)
print(accuracy_score(y_trainR, y_estimated2))
print(f1_score(y_trainR, y_estimated2, average=None))

0.9925
[0.99496222 0.99380421 0.98669891 0.99481865]


In [18]:
parameter_grid = {'n_neighbors': list(range(1,10)), 'p': [1, 2, 3, 4.7]}
X_trainR, X_testR, y_trainR, y_testR = train_test_split(x, y, test_size=1/5, shuffle=True, random_state=42)
gs_random = RandomizedSearchCV(estimator=KNeighborsClassifier(), param_distributions=parameter_grid, cv= 5,n_iter=100)
gs_random.fit(X_trainR, y_trainR)
print (gs_random.best_params_)
y_estimated = gs_random.predict(X_testR)
print(accuracy_score(y_testR, y_estimated))
print(f1_score(y_testR, y_estimated, average=None))

C:\Users\Florina\Anaconda3\lib\site-packages\sklearn\model_selection\_search.py:271: UserWarning: The total space of parameters 36 is smaller than n_iter=100. Running 36 iterations. For exhaustive searches, use GridSearchCV.
  % (grid_size, self.n_iter, grid_size), UserWarning)


{'p': 2, 'n_neighbors': 3}
0.975
[0.99038462 0.96216216 0.95081967 0.99107143]


In [17]:
y_estimated2 = gs_random.predict(X_trainR)
print(accuracy_score(y_trainR, y_estimated2))
print(f1_score(y_trainR, y_estimated2, average=None))

0.9925
[0.99496222 0.99380421 0.98669891 0.99481865]


Decizion Tree


In [19]:
X_trainT, X_testT, y_trainT, y_testT = train_test_split(x, y, test_size=1/5, shuffle=True, random_state=42)
params = {'max_features': ['auto', 'sqrt', 'log2'],
          'min_samples_split':list(range(2,15)), 
          'min_samples_leaf':list(range(2,11)),
         }
grid_search = GridSearchCV(estimator = DecisionTreeClassifier(), param_grid=params, scoring='accuracy', cv=5, 
                           return_train_score=True, iid=False)
grid_search.fit(X_trainT, y_trainT)
y_estimated = grid_search.predict(X_testT)
print(accuracy_score(y_testT, y_estimated))
print(grid_search.best_params_)
print(f1_score(y_testT, y_estimated, average=None))

0.9625
{'max_features': 'log2', 'min_samples_leaf': 2, 'min_samples_split': 4}
[0.98095238 0.94179894 0.92045455 0.99555556]


In [20]:
y_estimated2 = grid_search.predict(X_trainT)
print(accuracy_score(y_trainT, y_estimated2))
print(f1_score(y_trainT, y_estimated2, average=None))

0.99
[0.9924812  0.99138991 0.98292683 0.99349805]


In [10]:
gs_random = RandomizedSearchCV(estimator=DecisionTreeClassifier(), param_distributions=params, cv= 5,n_iter=100)
gs_random.fit(X_trainT, y_trainT)
print (gs_random.best_params_)


{'min_samples_split': 7, 'min_samples_leaf': 2, 'max_features': 'auto'}


In [26]:
y_estimated = gs_random.predict(X_testT)
print(accuracy_score(y_testT, y_estimated))
print(grid_search.best_params_)
print(f1_score(y_testT, y_estimated, average=None))

0.975
{'max_features': 'log2', 'min_samples_leaf': 2, 'min_samples_split': 7}
[0.99038462 0.96216216 0.95081967 0.99107143]


In [22]:
y_estimated2 = gs_random.predict(X_trainT)
print(accuracy_score(y_trainT, y_estimated2))
print(f1_score(y_trainT, y_estimated2, average=None))

0.9925
[0.99496222 0.99380421 0.98669891 0.99481865]


Random Forest

In [27]:
from sklearn.ensemble import RandomForestClassifier

paramsF = {'criterion':['gini','entropy'],
          'n_estimators':[10,15,20,25,30],
          'min_samples_leaf':[1,2,3],
          'min_samples_split':[3,4,5,6,7]}
X_trainF, X_testF, y_trainF, y_testF = train_test_split(x, y, test_size=1/5)
grid_search = GridSearchCV(estimator = RandomForestClassifier(), param_grid=paramsF, scoring='accuracy', cv=5, 
                           return_train_score=True, iid=False)
grid_search.fit(X_trainF, y_trainF)
y_estimated = grid_search.predict(X_testF)
print(accuracy_score(y_testF, y_estimated))
print(grid_search.best_params_)
print(f1_score(y_testF, y_estimated, average=None))

0.985
{'criterion': 'entropy', 'min_samples_leaf': 2, 'min_samples_split': 3, 'n_estimators': 25}
[1.         0.97777778 0.96629213 0.99065421]


In [29]:
y_estimated = grid_search.predict(X_trainF)
print(accuracy_score(y_trainF, y_estimated))
print(grid_search.best_params_)
print(f1_score(y_trainF, y_estimated, average=None))

0.996875
{'criterion': 'entropy', 'min_samples_leaf': 2, 'min_samples_split': 3, 'n_estimators': 25}
[0.99740933 0.99632803 0.99514563 0.99872935]


In [31]:
gs_randomF = RandomizedSearchCV(estimator=RandomForestClassifier(), param_distributions=paramsF, cv= 5,n_iter=100)
gs_randomF.fit(X_trainF, y_trainF)
print (gs_randomF.best_params_)
y_estimatedF = gs_randomF.predict(X_testF)
print(accuracy_score(y_testF, y_estimatedF))
print(f1_score(y_testF, y_estimatedF, average=None))

{'n_estimators': 25, 'min_samples_split': 4, 'min_samples_leaf': 3, 'criterion': 'gini'}
0.985
[1.         0.97777778 0.96629213 0.99065421]


In [32]:
y_estimatedF = gs_randomF.predict(X_trainF)
print(accuracy_score(y_trainF, y_estimatedF))
print(f1_score(y_trainF, y_estimatedF, average=None))

0.995625
[0.99870298 0.99262899 0.99153567 1.        ]


SVM

In [34]:
from sklearn import svm
paramsS = {'C': [6,7,8,9,10,11,12], 
          'kernel': ['linear','rbf']}
X_trainS, X_testS, y_trainS, y_testS = train_test_split(x, y, test_size=1/5)
grid_searchS = GridSearchCV(estimator = svm.SVC(gamma='auto'), param_grid=paramsS, scoring='accuracy', cv=5, 
                           return_train_score=True, iid=False)
grid_searchS.fit(X_trainS, y_trainS)
y_estimatedS = grid_searchS.predict(X_testS)
print(accuracy_score(y_testS, y_estimatedS))
print(grid_searchS.best_params_)
print(f1_score(y_testS, y_estimatedS, average=None))

0.985
{'C': 6, 'kernel': 'linear'}
[1.         0.98019802 0.97087379 0.98947368]


In [35]:
y_estimatedS = grid_searchS.predict(X_trainS)
print(accuracy_score(y_trainS, y_estimatedS))
print(f1_score(y_trainS, y_estimatedS, average=None))

0.98375
[0.99374218 0.97567222 0.97044335 0.9950495 ]


In [37]:
gs_randomS = RandomizedSearchCV(estimator=svm.SVC(gamma='auto'), param_distributions=paramsS, cv= 5,n_iter=100)
gs_randomS.fit(X_trainS, y_trainS)
print (gs_randomS.best_params_)
y_estimatedS = gs_randomS.predict(X_testS)
print(accuracy_score(y_testS, y_estimatedS))
print(f1_score(y_testS, y_estimatedS, average=None))

C:\Users\Florina\Anaconda3\lib\site-packages\sklearn\model_selection\_search.py:271: UserWarning: The total space of parameters 14 is smaller than n_iter=100. Running 14 iterations. For exhaustive searches, use GridSearchCV.
  % (grid_size, self.n_iter, grid_size), UserWarning)


{'kernel': 'linear', 'C': 6}
0.985
[1.         0.98019802 0.97087379 0.98947368]


In [38]:
y_estimatedS = gs_randomS.predict(X_trainS)
print(accuracy_score(y_trainS, y_estimatedS))
print(f1_score(y_trainS, y_estimatedS, average=None))

0.98375
[0.99374218 0.97567222 0.97044335 0.9950495 ]


Multi-layer Perceptron classifier

In [40]:
from sklearn.neural_network import MLPClassifier
paramsM = {'activation' : ['identity', 'logistic', 'tanh', 'relu'], 
          'solver' : ['lbfgs', 'sgd', 'adam'],
          'alpha':[0.1, 0.001, 0.0001]}
X_trainM, X_testM, y_trainM, y_testM = train_test_split(x, y, test_size=1/5)
grid_searchM = GridSearchCV(estimator = MLPClassifier(max_iter=10000), param_grid=paramsM, scoring='accuracy', cv=5, 
                           return_train_score=True, iid=False)
grid_searchM.fit(X_trainM, y_trainM)


GridSearchCV(cv=5, error_score='raise-deprecating',
       estimator=MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(100,), learning_rate='constant',
       learning_rate_init=0.001, max_iter=10000, momentum=0.9,
       n_iter_no_change=10, nesterovs_momentum=True, power_t=0.5,
       random_state=None, shuffle=True, solver='adam', tol=0.0001,
       validation_fraction=0.1, verbose=False, warm_start=False),
       fit_params=None, iid=False, n_jobs=None,
       param_grid={'activation': ['identity', 'logistic', 'tanh', 'relu'], 'solver': ['lbfgs', 'sgd', 'adam'], 'alpha': [0.1, 0.001, 0.0001]},
       pre_dispatch='2*n_jobs', refit=True, return_train_score=True,
       scoring='accuracy', verbose=0)

In [41]:
y_estimatedM = grid_searchM.predict(X_testM)
print(accuracy_score(y_testM, y_estimatedM))
print(grid_searchM.best_params_)
print(f1_score(y_testM, y_estimatedM, average=None))

0.975
{'activation': 'relu', 'alpha': 0.001, 'solver': 'adam'}
[0.98492462 0.97487437 0.94252874 0.99122807]


In [42]:
y_estimatedM = grid_searchM.predict(X_testM)
print(accuracy_score(y_testM, y_estimatedM))
print(f1_score(y_testM, y_estimatedM, average=None))

0.975
[0.98492462 0.97487437 0.94252874 0.99122807]


In [43]:
gs_randomM = RandomizedSearchCV(estimator=MLPClassifier(max_iter=10000), param_distributions=paramsM, cv= 5,n_iter=100)
gs_randomM.fit(X_trainM, y_trainM)
print (gs_randomM.best_params_)
y_estimatedM = gs_randomM.predict(X_testM)
print(accuracy_score(y_testM, y_estimatedM))
print(f1_score(y_testM, y_estimatedM, average=None))

C:\Users\Florina\Anaconda3\lib\site-packages\sklearn\model_selection\_search.py:271: UserWarning: The total space of parameters 36 is smaller than n_iter=100. Running 36 iterations. For exhaustive searches, use GridSearchCV.
  % (grid_size, self.n_iter, grid_size), UserWarning)


{'solver': 'lbfgs', 'alpha': 0.1, 'activation': 'tanh'}
0.98
[0.98989899 0.97512438 0.95402299 0.99559471]


In [44]:
y_estimatedM = gs_randomM.predict(X_trainM)
print(accuracy_score(y_trainM, y_estimatedM))
print(f1_score(y_trainM, y_estimatedM, average=None))

0.984375
[0.99626401 0.97610063 0.97218863 0.99354839]
