# Laborator 2

Saptamana 2-6 martie 2020

Continut:
1. Setup
1. Exercitii cu functii
1. Exercitii cu NumPy

## Setup

Formati ecipe de cate doi. Creati un repository *privat* pe github, cu numele: IDS_NumeFamilieStudent1_NumeFamilieStudent2. Indiferent de grupa din care faceti parte, adaugati ca si colaboratori pe acest repo utilizatorii: akerestely si lmsasu.

Resurse:
1. [Setare de repository privat](https://help.github.com/en/github/administering-a-repository/setting-repository-visibility)
1. [Clienti de git](https://www.hostinger.com/tutorials/best-git-gui-clients/)

## Exercitii cu functii

Nota: aceste exercitii nu se puncteaza. 

1. Sa se scrie o functie care primeste ca parametru o lista de numere si returneaza un tuplu continand: suma elementelor si diferenta maxima dintre elementele listei.
1. Scrieti o functie care preia doua liste si returneaza `True` daca cele doua liste de numere contin cel putin $k$ elemente comune ($k \ge 1$ dat ca parametru intreg, valoare implicita 1), `False` altfel.
1. Sa se scrie o functie care determina daca o lista contine cuvinte reprezentand doar numere intregi (optional: numere fractionare, scrise sub forma parte intreaga, optional urmata de punct zecimal, optional urmata de parte fractionara: 1, 2., 13.14) (Puteti folosi modulul `re` pentru lucrul cu expresii regulate.) Functia trebuie sa testeze daca:
    1. elementele din lista sunt stringuri
    2. fiecare din stringuri este un numar
1. Sa se scrie o functie care returneaza numarul de vocale si de consoane dintr-un parametru dat - rezultatul returnat de functie este tuplu cu doua valori. Cuvantul se va converti la litere mici in interiorul functiei.
1. Sa se scrie o functie care primind o lista de dictionare, returneaza `True` daca toate dictionarele contin cel putin $n$ elemente, $n$ transmis ca parametru, `False` altfel.
1. Sa se scrie o functie recursiva care sa faca ridicarea la putere a unui numar, astfel:
$$
a^n = \begin{cases}
a & \text{daca }n=1
\\
\left(a^{n//2}\right)^2 & \text{daca } n \text{ e par}
\\
\left(a^{n//2}\right)^2 \cdot a & \text{daca } n \text{ e impar}, n>1
\\
\end{cases}
$$
unde prin $n//2$ se reprezinta catul impartirii intregi intre $n$ si 2.

## Exercitii simple folosind NumPy  

Nota: in rezolvarea exercitiilor se vor folosi cat mai mult functii NumPy *vectorizate*. Functiile scrise de voi vor fi documentate cu docstrings (tutoriale: Docstrings in Python, urmati NumPy Style Python Docstrings). Folositi type annotations. Utilizati doar pachetele NumPy.

1. (0.5 puncte) Pentru un vector NumPy dat, sa se determine care sunt elementele unice, in ordine descrescatoare. Exemplu: pentru `x = np.array([-4, 3,  5, 3, 2, 1, -3, -4, 2, -4])` functia scrisa de dvs va intoarce rezultatul `[ 5,  3,  2,  1, -3, -4]`.
1. (0.5 puncte) Pentru un vector NumPy dat, sa se determine care e elementul cel mai frecvent si cel mai putin frecvent (tuplu de 2 valori). Daca exista mai multe numere cele mai frecvente (cele mai putin frecvente), se va raporta oricare din ele. Exemplu: pentru `x = np.array([-4, 3,  5, 3, 2, 1, -3, -4, 2, -4])` functia scrisa de dvs va intoarce rezultatul `(-4, -3)`. 
1. (0.5 puncte) Plecand de la o matrice, sa se scrie o functie care returneaza vectorul minimelor de pe linii si vectorul maximelor de pe coloane. Exemplu: pentru matricea `mat = np.array([[1, 2, 3, 4], [1, -2, 3, -4], [3, 10, 3, 4]])` functia va returna tuplul de vectori: `(array([ 1, -4,  3]), array([ 3, 10,  3,  4]))`. Indicatie:  folositi-va de parametrul `axis`.
1. (0.5 puncte) Pentru o matrice de numere, sa se determine produsul elementelor pe linii sau de pe coloane, in functie de valoarea unui parametru boolean `compute_on_lines`. Exemplu: pentru matricea `mat = np.array([[1, 2, 3, 4], [1, -2, 3, -4], [3, 10, 3, 4]])` si parametrul `compute_on_lines=True`, functia va returna vectorul `[ 24  24 360]`, iar pentru `compute_on_lines=False` se va returna `[  3 -40  27 -64]`.
1. (0.5 puncte) Determinati daca macar unul din elementele unei matrice `a` este mai mare decat cel de pe pozitie corespondenta din `b` (adica daca avem macar o pereche de indecsi (i, j) pentru care a[i, j] > b[i, j]). Daca da, se va returna o astfel de pereche de indecsi; daca nu, se va returna None.
1. (0.5 puncte) Construiti o functie care, primind o matrice, determina pe ce pozitii se afla valorile in afara unui interval [min, max] dat prin parametri.
1. (1 punct) Se considera vectorul: `a = np.array([230, 10, 284, 39, 76])`. Folosind indexarea logica, sa se inmulteasca elementele din vector care sunt mai mici ca 100 cu 2 (restul raman neschimbate). Folosind ciclare, sa se aplice aceeasi operatie pana cand toate elementele devin mai mari ca 100. Sa se afiseze din vectorul final elementele care sunt mai mari de 150 si mai mici de 200.
1. (1 punct) Sa se scrie o functie `pair_max` care preia doi vectori de aceeasi lungime si returneaza maximele pe pozitiile corespunzatoare:
```python
a = np.array([3, 7, 9, 13, -10, 200, 3])
b = np.array([4, 5, -9, 100, 300, 230, 1])
pair_max(a, b)
#iesire dorita: 
array([  4,   7,   9, 100, 300, 230,   3])
```. Functia va verifica cu `assert` ca vectorii au lungimi egale. 
1. (1 punct) Descarcati setul de date Iris de la adresa 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data', si incarcati-l intr--o matrice NumPy, folosind `np.genfromtxt`.  Alegeti aleator 10 pozitii in matricea de 150 linii si 4 coloane (omiteti ultima coloana, de tip text), setati aceste valori pe NaN. Construiti o functie care, primind la intrare o matrice, returneaza un tuplu cu indicii de linii respectiv de coloane in care se gasesc valori NaN.
1. (1 punct) Sa se construiasca o functie care returneaza cele mai mici `k` valori dintr-un vector de cel putin `k` elemente, impreuna cu pozitiile lor. 

## Precizari
1. Se acorda 3 puncte din oficiu.
1. Tema se va prezenta in saptamana 16-20 martie 2020. 
1. Repository-ul va contine un fisier "README.md" (in radacina repository-ului) in care vor fi mentionati autorii temelor, cu nume complet si grupa din care fac parte.

In [17]:
#functii ex 1
num=[1,2,3,4,5,6,7,8,9]
def f1(list):
    s=0
    difmax=0
    max=0
    min=500
    for x in num:
        s=s+x
        if x<min:
            min=x 
        if x>max:
            max=x 
  
    print("suma numerelor este ", s )
    print(" diferenta maxima este ",max-min)

f1(list)


suma numerelor este  45
 diferenta maxima este  8


In [18]:
#functii ex 2
num1=[3,4,5,6,7,8]
num2=[1,2,3,4,5,6]
def f2(num1,num2,k:int):
    c=0
    k=1
    for x in num1:
        for y in num2:
            if x==y:
                c=c+1
    if c>=k:
        return True
    else:
        return False
    
f2(num1,num2,k)
                

NameError: name 'k' is not defined

In [19]:
#functii ex 3
import re
import numpy as np
from typing import List

def checker3(lista:List[str])->bool:
    if all(isinstance(item, str) for item in lista)==False:
        return "Lista nu contine numai stringuri!"
    reg_float = r'^[+-]?\d+.?\d*$'
    all_float = all([re.match(reg_float, item) for item in lista])
    return all_float


lista = ['1','2']
checker3(lista)

True

In [20]:
#numpy ex1
x = np.array([-4, 3,  5, 3, 2, 1, -3, -4, 2, -4],int ) 
def revuniques(x): 
    uniques = np.unique(x)
    np.sort(uniques)
    print(uniques[::-1])
"""Functia primeste  un np.array de valori int si elimina datele duplicate
param :date de intrare sub forma de np.array"""
revuniques(x) 

[ 5  3  2  1 -3 -4]


In [21]:
#numpy ex3
mat = np.array([[1, 2, 3, 4], [1, -2, 3, -4], [3, 10, 3, 4]])
def arraysort(mat):
    min=np.amin(mat, axis=0)   
    max=np.amax(mat, axis=1) 

    print("array1(",min,")" )
    print("array2(",max,")" )
    """Functia primeste 2 np.array si modifica si afiseaza perechile si formeaza un array de minime pe randuri 
    si unul de maxime pe coloana 
param :date de intrare sub forma de np.array"""
arraysort(mat)

array1( [ 1 -2  3 -4] )
array2( [ 4  3 10] )


In [22]:
#numpy ex 4
mat = np.array([[1, 2, 3, 4], [1, -2, 3, -4], [3, 10, 3, 4]])
def prod(compute_on_lines:bool,mat):
    result=np.array([]);
    if compute_on_lines==True:
        result=[np.prod(row) for row in mat]
    else:
        result=[np.prod([row[i] for row in mat]) for i in range(0,len(mat[0]))]
    return result

print(prod(False,mat))
print(prod(True,mat))

[3, -40, 27, -64]
[24, 24, 360]


In [23]:
#numpy ex 2
from typing import Tuple
from typing import Counter
x = np.array([-4, 3,  5, 3, 2, 1, -3, -4, 2, -4])

def mostAndLeastCommunElement(x)->Tuple[float,float]:
    b = Counter(x)
    return b.most_common(1)[0][0],b.most_common(1)[0][1]

mostAndLeastCommunElement(x)

(-4, 3)

In [24]:
#numpy ex5
import numpy as np
a = np.array([[1, 2, 3, 4], [1, -2, 3, -4], [3, 10, 9, 4]]) 
b = np.array([[1, 1, 3, 5], [1, 4, 3, -4], [3, 10, 3, 5]])
def arraycompare(a,b):
    print ("original array a: \n" ,a)
    print("\n original array b: \n",b)
    solutions = np.argwhere(a> b)
    print("indecsi unde a>b: \n",solutions)

    """Functia primeste 2 np.array si modifica si afiseaza perechile de indici unde a[i][j]>b[i][j] 
param :date de intrare sub forma de np.array"""

arraycompare(a,b)

original array a: 
 [[ 1  2  3  4]
 [ 1 -2  3 -4]
 [ 3 10  9  4]]

 original array b: 
 [[ 1  1  3  5]
 [ 1  4  3 -4]
 [ 3 10  3  5]]
indecsi unde a>b: 
 [[0 1]
 [2 2]]


In [28]:
#numpy ex 7
a = np.array([230, 10, 284, 39, 76])
def ecxtractfunction(a):
    a[a<100]*=2
    while any(a<100):
        a[a<100]*=2
    print(a)
    print(a[np.logical_and(a>150,a<200)])
ecxtractfunction(a)
    """Functia primeste un np.array si modifica si afiseaza valori di acesta
param :date de intrare sub forma de np.array"""


IndentationError: unexpected indent (<ipython-input-28-adbf5359b730>, line 10)

In [27]:
#numpy ex 9
from typing import Tuple
mat=np.genfromtxt("iris.data",dtype=float,delimiter=",")
m=mat[:,:,-1]
lines=np.random.random_integers(0,149,size=(10,))
colums=np.random.random_integers(0,3,size=(10,))
m[lines,colums]=np.nan
def nan_function(mat:np.array)->Tuple:
    indices=np.where(np.isnan(m))
    return indices[0],indices[1]
nan_function(mat)
"""Functia primeste o matrice si returneaza un tuplu de indici
param mat:date de intrare sub forma de np.array(m,n)
date iesire: tuplu de indici"""

IndexError: too many indices for array