# Laborator 2 - Teme
<br>
Autori:
Taraburca Radu,
Vlasie Rares


## Exercitii cu functii
<br>


In [86]:
import numpy as np
from typing import List,Tuple

1 Sa se scrie o functie care primeste ca parametru o lista de numere si returneaza un 
 tuplu continand: suma elementelor si diferenta maxima dintre elementele listei.


In [87]:

def sTuplu(lista):
    suma=0
    for i in lista:
        suma+=i
    lista.sort()
    dif=lista[-1]-lista[0]
    pair=(suma,dif)
    return pair
    
lista=[4,2,3]
sTuplu(lista)

(9, 2)

 2 Scrieti o functie care preia doua liste si returneaza True daca cele doua liste de numere 
contin cel putin  k  elemente comune ( k≥1  dat ca parametru intreg, valoare implicita 1), False altfel.


In [88]:

def checkKCommunElements(lista1:List[float],lista2:List[float],k:int=1)->bool:
    nrk=0
    for i in lista1:
        for j in lista2:
            if(i==j):
                nrk+=1
    if nrk>=k:
        return True
    else:
        return False
    
lista=[4,2,3]
lista2=[0,2,3]

checkKCommunElements(lista,lista2)

True

3.Sa se scrie o functie care determina daca o lista contine cuvinte reprezentand doar numere intregi 
(optional: numere fractionare, scrise sub forma parte intreaga, optional urmata de punct zecimal, optional urmata de parte fractionara: 1, 2., 13.14) (Puteti folosi modulul re pentru lucrul cu expresii regulate.) 
<br>
<br>
Functia trebuie sa testeze daca:
    <br>A.elementele din lista sunt stringuri
    <br>    B.fiecare din stringuri este un numar

In [89]:

import re

def checker3(lista:List[str])->bool:
    if all(isinstance(item, str) for item in lista)==False:
        return "Lista nu contine numai stringuri!"
    reg_float = r'^[+-]?\d+\.?\d*$'
    all_float = all([re.match(reg_float, item) for item in lista])
    return all_float
                

lista = ['1','2']
checker3(lista)

True

4.Sa se scrie o functie care returneaza numarul de vocale si de consoane dintr-un parametru dat-rezultatul returnat de functie 
este tuplu cu doua valori. Cuvantul se va converti la litere mici in interiorul functiei.

5. Sa se scrie o functie care primind o lista de dictionare, returneaza `True` daca toate dictionarele contin cel putin $n$ elemente, $n$ transmis ca parametru, `False` altfel.


6. Sa se scrie o functie recursiva care sa faca ridicarea la putere a unui numar, astfel:
$$
a^n = \begin{cases}
a & \text{daca }n=1
\\
\left(a^{n//2}\right)^2 & \text{daca } n \text{ e par}
\\
\left(a^{n//2}\right)^2 \cdot a & \text{daca } n \text{ e impar}, n>1
\\
\end{cases}
$$
unde prin $n//2$ se reprezinta catul impartirii intregi intre $n$ si 2.

## Exercitii simple folosind NumPy  

Nota: in rezolvarea exercitiilor se vor folosi cat mai mult functii NumPy *vectorizate*. Functiile scrise de voi vor fi documentate cu docstrings (tutoriale: Docstrings in Python, urmati NumPy Style Python Docstrings). Folositi type annotations. Utilizati doar pachetele NumPy.

1. (0.5 puncte) Pentru un vector NumPy dat, sa se determine care sunt elementele unice, in ordine descrescatoare. Exemplu: pentru `x = np.array([-4, 3,  5, 3, 2, 1, -3, -4, 2, -4])` functia scrisa de dvs va intoarce rezultatul `[ 5,  3,  2,  1, -3, -4]`.


In [429]:
x = np.array([-4, 3,  5, 3, 2, 1, -3, -4, 2, -4],int ) 
def revuniques(x): 
    uniques = np.unique(x)
    np.sort(uniques)
    return uniques[::-1]
    
print(revuniques(x))

"""Functia primeste  un np.array de valori int si elimina datele duplicate
param :date de intrare sub forma de np.array"""

[ 5  3  2  1 -3 -4]


'Functia primeste  un np.array de valori int si elimina datele duplicate\nparam :date de intrare sub forma de np.array'

2. (0.5 puncte) Pentru un vector NumPy dat, sa se determine care e elementul cel mai frecvent si cel mai putin frecvent (tuplu de 2 valori). Daca exista mai multe numere cele mai frecvente (cele mai putin frecvente), se va raporta oricare din ele. Exemplu: pentru `x = np.array([-4, 3,  5, 3, 2, 1, -3, -4, 2, -4])` functia scrisa de dvs va intoarce rezultatul `(-4, -3)`. 


In [424]:
from collections import Counter


In [431]:
x = np.array([-4, 3,  5, 3, 2, 1, -3, -4, 2, -4])

def mostAndLeastCommunElement(x)->Tuple[float,float]:
    b = Counter(x)
    return b.most_common(1)[0][0],b.most_common(1)[0][1]

print(mostAndLeastCommunElement(x))

"""Functia primeste un numpay array de valori float si intoarce un tuplu format din cel mai frecvent
si cel mai putin frecvent element din array """

(-4, 3)


'Functia primeste un numpay array de valori float si intoarce un tuplu format din cel mai frecvent\nsi cel mai putin frecvent element din array '

3. (0.5 puncte) Plecand de la o matrice, sa se scrie o functie care returneaza vectorul minimelor de pe linii si vectorul maximelor de pe coloane. Exemplu: pentru matricea `mat = np.array([[1, 2, 3, 4], [1, -2, 3, -4], [3, 10, 3, 4]])` functia va returna tuplul de vectori: `(array([ 1, -4,  3]), array([ 3, 10,  3,  4]))`. Indicatie:  folositi-va de parametrul `axis`.


In [440]:
mat = np.array([[1, 2, 3, 4], [1, -2, 3, -4], [3, 10, 3, 4]])
def arraysort(mat)->Tuple[np.array,np.array]:
    min=np.amin(mat, axis=1)
    max=np.amax(mat, axis=0)
    return min,max
    
print(arraysort(mat))

"""Functia primeste 2 np.array si modifica si afiseaza perechile si formeaza un array de minime pe randuri 
    si unul de maxime pe coloana 
    param :date de intrare sub forma de np.array"""

(array([ 1, -4,  3]), array([ 3, 10,  3,  4]))


'Functia primeste 2 np.array si modifica si afiseaza perechile si formeaza un array de minime pe randuri \n    si unul de maxime pe coloana \n    param :date de intrare sub forma de np.array'

4. (0.5 puncte) Pentru o matrice de numere, sa se determine produsul elementelor pe linii sau de pe coloane, in functie de valoarea unui parametru boolean `compute_on_lines`. Exemplu: pentru matricea `mat = np.array([[1, 2, 3, 4], [1, -2, 3, -4], [3, 10, 3, 4]])` si parametrul `compute_on_lines=True`, functia va returna vectorul `[ 24  24 360]`, iar pentru `compute_on_lines=False` se va returna `[  3 -40  27 -64]`.


In [442]:
mat = np.array([[1, 2, 3, 4], [1, -2, 3, -4], [3, 10, 3, 4]])
def prod(compute_on_lines:bool,mat):
    result=np.array([]);
    if compute_on_lines==True:
        result=[np.prod(row) for row in mat]
    else:
        result=[np.prod([row[i] for row in mat]) for i in range(0,len(mat[0]))]
    return result

print(prod(False,mat))
print(prod(True,mat))
"""Functia primeste o valoare booleana si o matrice de tipul numpay array si intoarce in functie de valoare booleana, un 
numpay array cu valori reprezentand produsul elementelor de pe linii sau de pe coloane"""
    

[3, -40, 27, -64]
[24, 24, 360]


'Functia primeste o valoare booleana si o matrice de tipul numpay array si intoarce in functie de valoare booleana, un \nnumpay array cu valori reprezentand produsul elementelor de pe linii sau de pe coloane'

5. (0.5 puncte) Determinati daca macar unul din elementele unei matrice `a` este mai mare decat cel de pe pozitie corespondenta din `b` (adica daca avem macar o pereche de indecsi (i, j) pentru care a[i, j] > b[i, j]). Daca da, se va returna o astfel de pereche de indecsi; daca nu, se va returna None.


In [441]:
a = np.array([[1, 2, 3, 4], [1, -2, 3, -4], [3, 10, 9, 4]]) 
b = np.array([[1, 1, 3, 5], [1, 4, 3, -4], [3, 10, 3, 5]])
def arraycompare(a,b):
    print ("original array a: \n" ,a)
    print("\n original array b: \n",b)
    solutions = np.argwhere(a> b)
    print("indecsi unde a>b: \n",solutions)

print(arraycompare(a,b))

"""Functia primeste 2 np.array si modifica si afiseaza perechile de indici unde a[i][j]>b[i][j] 
param :date de intrare sub forma de np.array"""

original array a: 
 [[ 1  2  3  4]
 [ 1 -2  3 -4]
 [ 3 10  9  4]]

 original array b: 
 [[ 1  1  3  5]
 [ 1  4  3 -4]
 [ 3 10  3  5]]
indecsi unde a>b: 
 [[0 1]
 [2 2]]
None


'Functia primeste 2 np.array si modifica si afiseaza perechile de indici unde a[i][j]>b[i][j] \nparam :date de intrare sub forma de np.array'

6. (0.5 puncte) Construiti o functie care, primind o matrice, determina pe ce pozitii se afla valorile in afara unui interval [min, max] dat prin parametri.


In [445]:
mat = np.array([[1, 2, 3, 4], [1, -2, 3, -4], [3, 10, 3, 4]])
def positionNotFromInterval(mat,minpoz:float,maxpoz:float):
    a=np.where((mat >maxpoz) | (mat<minpoz))
    c=a[0].tolist()
    b=a[1].tolist()  
    return np.column_stack((c, b))

print(positionNotFromInterval(mat,2,10))
"""Functia primeste o matrice de tipul numpay array, un minim si un maxim de tip float si intoarce un numpay array care contine 
 pozitiile valorilor din array in afara intervalului reprezentat de  [minim, maxim] """

[[0 0]
 [1 0]
 [1 1]
 [1 3]]


'Functia primeste o matrice de tipul numpay array, un minim si un maxim de tip float si intoarce un numpay array care contine \n pozitiile valorilor din array in afara intervalului reprezentat de  [minim, maxim] '

7. (1 punct) Se considera vectorul: `a = np.array([230, 10, 284, 39, 76])`. Folosind indexarea logica, sa se inmulteasca elementele din vector care sunt mai mici ca 100 cu 2 (restul raman neschimbate). Folosind ciclare, sa se aplice aceeasi operatie pana cand toate elementele devin mai mari ca 100. Sa se afiseze din vectorul final elementele care sunt mai mari de 150 si mai mici de 200.


In [413]:
a = np.array([230, 10, 284, 39, 76])
def ecxtractfunction(a):
    a[a<100]*=2
    while any(a<100):
        a[a<100]*=2
        print(a)
        print(a[np.logical_and(a>150,a<200)])
ecxtractfunction(a)
"""Functia primeste un np.array si modifica si afiseaza valori di acesta param :date de intrare sub forma de np.array"""

[230  40 284 156 152]
[156 152]
[230  80 284 156 152]
[156 152]
[230 160 284 156 152]
[160 156 152]


'Functia primeste un np.array si modifica si afiseaza valori di acesta param :date de intrare sub forma de np.array'

8. (1 punct) Sa se scrie o functie `pair_max` care preia doi vectori de aceeasi lungime si returneaza maximele pe pozitiile corespunzatoare:
```python
a = np.array([3, 7, 9, 13, -10, 200, 3])
b = np.array([4, 5, -9, 100, 300, 230, 1])
pair_max(a, b)
#iesire dorita: 
array([  4,   7,   9, 100, 300, 230,   3])
```. Functia va verifica cu `assert` ca vectorii au lungimi egale. 


In [448]:
a = np.array([3, 7, 9, 13, -10, 200, 3])
b = np.array([4, 5, -9, 100, 300, 230, 1])

def pair_max(a, b):
    mat= np.concatenate((a, b.T))
    mat=mat.reshape(2,len(a))
    result=[np.max([row[i] for row in mat]) for i in range(0,len(mat[0]))]
    return result

    
print(pair_max(a, b))
"""Funtia primeste ca parametrii 2 array uri de tipul numpay array si returneaza un numpay array cu valorile maxime de pe pozitiile
corespunzatoare din fiecare array"""

[4, 7, 9, 100, 300, 230, 3]


'Funtia primeste ca parametrii 2 array uri de tipul numpay array si returneaza un numpay array cu valorile maxime de pe pozitiile\ncorespunzatoare din fiecare array'

9. (1 punct) Descarcati setul de date Iris de la adresa 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data', si incarcati-l intr--o matrice NumPy, folosind `np.genfromtxt`.  Alegeti aleator 10 pozitii in matricea de 150 linii si 4 coloane (omiteti ultima coloana, de tip text), setati aceste valori pe NaN. Construiti o functie care, primind la intrare o matrice, returneaza un tuplu cu indicii de linii respectiv de coloane in care se gasesc valori NaN.


In [415]:
mat=np.genfromtxt("iris.data",dtype=float,delimiter=",")
m=mat[:,:-1]

lines=np.random.randint(0,149,size=(10,))
colums=np.random.randint(0,3,size=(10,))
m[lines,colums]=np.nan

def nan_function(mat:np.array)->Tuple:
    indices=np.where(np.isnan(m))
    return indices[0].tolist(),indices[1].tolist()

print(nan_function(mat))

"""Functia primeste o matrice si returneaza un tuplu de indici
param mat:date de intrare sub forma de np.array(m,n)
date iesire: tuplu de indici"""

([11, 15, 42, 51, 63, 64, 84, 107, 133, 135], [0, 2, 0, 2, 2, 2, 1, 2, 0, 2])


'Functia primeste o matrice si returneaza un tuplu de indici\nparam mat:date de intrare sub forma de np.array(m,n)\ndate iesire: tuplu de indici'

10. (1 punct) Sa se construiasca o functie care returneaza cele mai mici `k` valori dintr-un vector de cel putin `k` elemente, impreuna cu pozitiile lor. 

In [449]:
a = np.array([3, 7, 9, 13, -10, 200, 3])

def returnfirtKSmall(arr,k):
    if(len(arr)<k):
        return "Vectorul nu contine " +str(k)+ " elemente"
    aux=np.sort(arr)
    aux=aux[:k]
    aux2=[np.where(a==i) for i in aux] 
    return aux2
        
        
    

aux=returnfirtKSmall(a,3)
print(aux)
"""Functia primeste un numpay array si o valoare k de tip int si funtia returneaza primele k elemente mici"""

[(array([4], dtype=int64),), (array([0, 6], dtype=int64),), (array([0, 6], dtype=int64),)]


'Functia primeste un numpay array si o valoare k de tip int si funtia returneaza primele k elemente mici'